### ISSUE TITLE
[question] Help with Missing Success Events in Quality SLO Evaluation - prometheusIngester

### ISSUE THREAD

**Issue by ocristian** [seznam/slo-exporter#120]
Hi there,

I recently had an issue with one of our quality SLOs, causing alerts to trigger unexpectedly. After investigating, I found that the `success events were not computed` in `prometheusIngester`, even though the Prometheus metric itself has available data when queried directly.

It looks like the missing success events led to alerts firing, as only failure events were detected.

I’m looking for guidance on:
1. Detecting missing events, how to identify when one type of event (success or failure) isn't being processed, to avoid false alerts.
2. Preventing this issue, how to ensure both success and failure events are always computed.

I checked the `slo-exporter` logs, but found no errors. I also enabled `DEBUG` logging temporarily, but since the issue isn’t reproducible, I couldn’t find any clues.

It's worth mentioning that this issue was observed after a POD eviction, in the newly started POD, whereas the previous POD was functioning as expected. The problem appeared in the new POD after the eviction and was resolved by redeploying `slo-exporter.`

If you’ve similar issue or have troubleshooting tips, I’d really appreciate your insights!

Thanks in advance—let me know if you need more details.

**Comment by FUSAKLA** [comment]
Hi, would you mind sharing the slo-exporter configuration you are using?

Regarding what you describe… I'd recommend checking the `slo_exporter_prometheus_ingester_query_fails_total` metric but if you say that there is no error in the logs, it seems that it won't be a case of failed query.

Regarding the rollout, just to make sure, it is running as statefuleset meaning there is no overlap of the old and new pod in time right? That could definitely lead to some unexpected behavior.

Another thing that comes to my mind is that the shutdown could happen during the querying causing one of the queries (success events query in your case) to fail but the other to succeed leading to inconsistency in the counts. But I'd hope there is a graceful shutdown handled.

Anyway, if you have separate queries for success and failed events, it could lead to inconsistencies since IIRC it is not atomic operation of executing all the queries at once since it can have different interval. I'd recommend (if possible) using single query and evaluate which events are success/failure later in the pipeline as shown in the [example here](https://github.com/seznam/slo-exporter/blob/master/examples/prometheus/slo_exporter.yaml#L27) and [here](https://github.com/seznam/slo-exporter/blob/master/examples/prometheus/slo_rules.yaml#L8).

**Comment by ocristian** [comment]
Hi @FUSAKLA , thanks for your quick reply!

Here are the details:

- Metric: `slo_exporter_prometheus_ingester_query_fails_total` – its value is 0.
- Rollout Strategy: The application is using a `Deployment/ReplicaSet`, meaning it is `stateless`.
- Graceful Shutdown: Yes, we have it in place. That’s a good point, perhaps increasing the shutdown duration could give more time to process events before termination.

Here the slo-exporter configuration:

_slo_exporter.yaml_
```
maximumGracefulShutdownDuration: "10s"
afterPipelineShutdownDelay: "1s"

webServerListenAddress: '0.0.0.0:8080'

pipeline: ["prometheusIngester", "eventKeyGenerator", "metadataClassifier", "sloEventProducer", "prometheusExporter"]

modules:
  prometheusIngester:
    apiUrl: "https://thanos.env.com"
    queryTimeout: 60s
    queries:
      - type: counter_increase
        query: 'service_exception_total'
        interval: 60s
        dropLabels:
          - environment_type
          - prometheus
          - prometheus_replica
          - environment
        additionalLabels:
          event_type: exceptions
          class: error
          status: fail

      - type: counter_increase
        query: 'serve_route_duration_seconds_by_code_count{code!~"5.*"}'
        interval: 30s
        dropLabels:
          - environment_type
          - prometheus
          - prometheus_replica
          - environment
          - route
        additionalLabels:
          event_type: exceptions
          class: error

  eventKeyGenerator:
    metadataKeys:
      - service_name

  metadataClassifier:
    sloDomainMetadataKey: service_name
    sloClassMetadataKey: class
    sloAppMetadataKey: event_type
    overrideExistingValues: true

  sloEventProducer:
    exposeRulesAsMetrics: true
    rulesFiles:
      - "/config/error/slo_rules.yaml"

  prometheusExporter:
    metricName: "slo_events_total"
    maximumUniqueEventKeys: 5000
    ExceededKeyLimitPlaceholder: "cardinalityLimitExceeded"
    labelNames:
      result: "result"
      sloDomain: "slo_domain"
      sloClass: "slo_class"
      sloApp: "slo_app"
      eventKey: "event_key"

```

_slo_rules.yaml_

```
rules:
  - metadata_matcher:
      - key: event_type
        operator: isEqualTo
        value: exceptions
    failure_conditions:
      - key: status
        operator: isEqualTo
        value: fail
    additional_metadata:
      slo_type: quality

```

Once again, thanks for your help! 
I'll take another look, and if I find anything, I can share it here.

**Comment by FUSAKLA** [comment]
Yeah, I'd suggest switching to stateful set from deployment, as the example [suggests](https://github.com/seznam/slo-exporter/blob/master/kubernetes/slo-exporter-statefulset.yaml). Unfortunately, it is difficult to have HA with Prometheus exporters, so you should avoid situations when multiple instances are running in parallel (which stateful set does).

Also, I suggest (if possible) instead of using `service_exception_total` for tracking the fails, use the `serve_route_duration_seconds_by_code_count{code=~"5.*"}`?

You can do it the way I linked in the previous reply, do not filter the status codes in the query just use 

```yaml
- type: counter_increase
        query: 'serve_route_duration_seconds_by_code_count'
        interval: 30s
        dropLabels:
          - environment_type
          - prometheus
          - prometheus_replica
          - environment
          - route
        additionalLabels:
          event_type: exceptions
          class: error
```

and then evaluate failures using the `failure_conditions` as [here](https://github.com/seznam/slo-exporter/blob/da4f7c5e0b1c30575a231040fa04e0581f8cb112/examples/prometheus/slo_rules.yaml#L9)

This way both, success and failed events, would come from single query and will be definitely more reliable.
